name: Restful web service
on:
  pull_request:
    types: [opened, edited]
  push:
    branches:
      - main
      - 'dev-*'
      - 'feature/**'
    paths:
      - '.github/workflows/*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone code
        uses: actions/checkout@v3
      - name: Install MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'spring-database'
          mysql user: anbit
          mysql password: root
      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Install maven dependencies
        run: mvn clean install
      - name: Run unit test
        run: mvn test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Clone code
        uses: actions/checkout@v3
      - name: Install MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'spring-database'
          mysql user: anbit
          mysql password: root
      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Install maven dependencies
        run: mvn clean install
      - name: Run build
        run: mvn clean install -DskipTests
      - name: Deploy to server
        run: echo "Deploying ...."